version: '3'
services:
  front:
    build:
      context: './client'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: react-container
    networks:
      - mern-stack-network
    volumes:
      - ./client:/app/client
    depends_on:
      - backend
  backend:
    build:
      context: './api'
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: express-container
    networks:
      - mern-stack-network
    volumes:
      - ./api:/app/api
    depends_on:
      - mongo
    env_file:
      - ./api/.env
  mongo:
    image: "mongo:latest"
    ports:
      - 27017:27017
    container_name: mongo-container
    networks:
      - mern-stack-network
    volumes:
      - mongoData:/data/db
networks:
  mern-stack-network:
volumes:
  mongoData:



